# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0002_auto_20180123_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='homework_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='已提交作业数'),
        ),
    ]
