# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-01 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0004_studentinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='status',
            field=models.BooleanField(default=False, verbose_name='是否导出'),
        ),
    ]
