# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-07 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AUTHENTICATION', '0006_auto_20180306_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='stu_class',
        ),
        migrations.RemoveField(
            model_name='teacherinfo',
            name='tea_class',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_class',
            field=models.IntegerField(choices=[(1, '人工智能实践班'), (2, '虚拟现实实践班'), (3, '智能硬件实践班')], default=1, verbose_name='实践班'),
        ),
    ]
