# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOMEWORK', '0003_remove_upload_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
