# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-06 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEACHING', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadteacher',
            name='data_class',
            field=models.IntegerField(choices=[(1, '人工智能实践班'), (2, '虚拟现实实践班'), (3, '智能硬件实践班')], default=1, verbose_name='所属实践班'),
        ),
        migrations.AddField(
            model_name='uploadteacher',
            name='data_type',
            field=models.IntegerField(choices=[(1, '作业'), (2, '资料')], default=1, verbose_name='资料类型'),
        ),
    ]
