from AUTHENTICATION import USER_IDENTITY_STUDENT, USER_IDENTITY_TEACHER
from AUTHENTICATION import USER_IDENTITY_ADMIN


def expose_consts(request):
    consts = {
        'USER_IDENTITY_STUDENT': USER_IDENTITY_STUDENT,
        'USER_IDENTITY_TEACHER': USER_IDENTITY_TEACHER,
        'USER_IDENTITY_ADMIN': USER_IDENTITY_ADMIN,
    }
    return consts
